### ISSUE TITLE
why the function preproc do not resize box?

### ISSUE THREAD

**Issue by sicong-li** [zisianw/FaceBoxes.PyTorch#11]
in the function preproc 
`height, width, _ = image_t.shape
        image_t = preproc_for_test(image_t, self.img_dim, self.rgb_means)
        boxes_t[:, 0::2] /= width
        boxes_t[:, 1::2] /= height`

where preproc_for_test has resize image size ,but why there not have the same deal with box?

**Comment by zisianw** [comment]
Hi @TemiLee, since `boxes_t` is in 0-1 scale, we only need to normalize according to its corresponding cropped patch.

**Comment by sicong-li** [comment]
thanks @zisianw
