### ISSUE TITLE
ImportError:__cudaPopCallConfiguration

### ISSUE THREAD

**Issue by zihaozhang9** [zisianw/FaceBoxes.PyTorch#12]
After  Compile the nms:`./make.sh`
run `python3 test.py`:
Traceback (most recent call last):
  File "mytest.py", line 9, in <module>
    from utils.nms_wrapper import nms
  File "/home/nnir712/project/FaceBoxes.PyTorch-master/utils/nms_wrapper.py", line 9, in <module>
    from .nms.gpu_nms import gpu_nms
ImportError: /home/nnir712/project/FaceBoxes.PyTorch-master/utils/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

**Comment by zisianw** [comment]
Hi @zihaozhang9, I've never seen this error before. From looking around on the internet, some solutions suggested that it may be related to PyTorch or CUDA version , see [mmdetection/issues/66](https://github.com/open-mmlab/mmdetection/issues/66)

**Comment by zihaozhang9** [comment]
> 嗨@ zihaozhang9，我以前从未见过这个错误。通过在互联网上查看，一些解决方案表明它可能与PyTorch或CUDA版本有关，请参阅[mmdetection / issues / 66](https://github.com/open-mmlab/mmdetection/issues/66)

ok,thinks~

**Comment by zihaozhang9** [comment]
> 嗨@ zihaozhang9，我以前从未见过这个错误。通过在互联网上查看，一些解决方案表明它可能与PyTorch或CUDA版本有关，请参阅[mmdetection / issues / 66](https://github.com/open-mmlab/mmdetection/issues/66)

ok,thank~
