### ISSUE TITLE
Can it be used for vehicle testing?

### ISSUE THREAD

**Issue by zihaozhang9** [zisianw/FaceBoxes.PyTorch#13]
Hello author! I am a beginner, maybe my problem is relatively low. I hope I can get an answer. Thank you very much.

Can faceboxes be used for vehicle testing? I tried to use yolo for vehicle detection, but it was very slow. Yolo is a multi-target detector with a large network structure. If a single target detector, such as a faceboxes face detector, is trained with vehicle data, is it possible to get a vehicle detector?

**Comment by zisianw** [comment]
Hi @zihaozhang9 , it is possible to retrain the network directly with your data since the training code is released. Alternatively, you could also take FaceBoxes as a base network and modify the architecture.

**Comment by zihaozhang9** [comment]
> 嗨@ zihaozhang9，自培训代码发布以来，可以直接用您的数据重新训练网络。或者，您也可以将FaceBoxes作为基础网络并修改体系结构。

Ok, thanks for the answer, I will try. What do you think is the difference between a multi-target detection network and a single-target detection network? Less filter count? Less layers?

**Comment by zisianw** [comment]
You can read up on SSD, a general object detection network which FaceBoxes is based on. There are plenty of explanations or tutorials online that you will find helpful.

**Comment by zihaozhang9** [comment]
> 您可以阅读SSD，这是FaceBoxes所基于的通用对象检测网络。您可以在网上找到很多有用的解释或教程。

Ok, thank you very much. Your suggestion is very helpful to me.
