### ISSUE TITLE
result detect face fail

### ISSUE THREAD

**Issue by daisy2202** [zisianw/FaceBoxes.PyTorch#16]
i use your weights and detected image in FDDB  then show result detection face. I saw fail result. Example: 
![screenshot from 2019-02-15 08-53-14](https://user-images.githubusercontent.com/18476939/52829406-31189880-30ff-11e9-8c28-1f8dee6b109f.png)

**Comment by zisianw** [comment]
Hi @quynh22021996, do you have the filename of the image? Btw, are you using python3?

**Comment by daisy2202** [comment]
i use python3, filename:
![img_414](https://user-images.githubusercontent.com/18476939/52840129-ec0a5b80-312a-11e9-8b31-e3c42216692c.jpg)

**Comment by zisianw** [comment]
@quynh22021996 , sorry I'm not sure why that happen. By using the image you posted here, it worked on my side. Error might be coming from somewhere else.
![capture](https://user-images.githubusercontent.com/20707594/52842857-55926600-313b-11e9-84fa-62cdb9e59361.JPG)

**Comment by daisy2202** [comment]
Do you use public weights for model? @zisianw

**Comment by zisianw** [comment]
@quynh22021996 Yes, you can verify the md5 checksum for the uploaded FaceBoxes.pth: c6f4784bed25765a685b52251b31d470

**Comment by romavlasov** [comment]
Hi, I have the same issue but on the other photo (random from internet): [http://nibler.ru/uploads/users/11119/2015-09-11/umnee-ostalnyh-yazykah-_7929365765.jpg](url)
![tmp](https://user-images.githubusercontent.com/19425609/53041428-075fc880-3495-11e9-94e8-deef1eb57cfc.jpg)

On the photo from this issue everything is ok:
![tmp](https://user-images.githubusercontent.com/19425609/53041683-aa184700-3495-11e9-939d-2c9508f86721.jpg)

I do the calculations in the following way:
`
Code:

    import cv2
    import torch
    import numpy as np

    from data import cfg

    from utils.nms import py_cpu_nms
    from utils.box_utils import decode

    from models.faceboxes import FaceBoxes
    from layers.functions.prior_box import PriorBox

    def main():
        model = FaceBoxes(phase='test', size=None, num_classes=2)
        model.load_state_dict(torch.load('weights/model.pth'))
        model.eval()

        resize = 1
        image = cv2.imread('images/image1.jpg', cv2.IMREAD_COLOR).astype(np.float32)
        drawing = image.copy()
        image = cv2.resize(image, None, None, fx=resize, fy=resize, interpolation=cv2.INTER_LINEAR)
        height, width, _ = image.shape
        print(height, width)
        scale = torch.Tensor([width, height, width, height])

        image -= [104, 117, 123]
        image = image.transpose(2, 0, 1)
        image = torch.from_numpy(image).unsqueeze(0)
        output = model(image)
        loc, conf, dimension = output

        priorbox = PriorBox(cfg, dimension, (height, width), phase='test')
        priors = priorbox.forward()
        prior_data = priors.data
        boxes = decode(loc.data.squeeze(0), prior_data, cfg['variance'])
        boxes = boxes * scale / resize
        boxes = boxes.cpu().numpy()
        scores = conf.data.cpu().numpy()[:, 1]

        inds = np.where(scores > 0.5)[0]
        boxes = boxes[inds]
        scores = scores[inds]

        order = scores.argsort()[::-1][:5000]
        boxes = boxes[order]
        scores = scores[order]

        dets = np.hstack((boxes, scores[:, np.newaxis])).astype(np.float32, copy=False)
        keep = py_cpu_nms.py_cpu_nms(dets, 0.3)
        dets = dets[keep, :]
        dets = dets[:750, :]

        for d in dets:
            xmin, ymin, xmax, ymax, _ = d.astype(np.uint8)
            print(xmin, ymin, xmax, ymax)
            cv2.rectangle(drawing, (xmin, ymin), (xmax, ymax), (32,255,32), 2)
        cv2.imwrite('tmp.jpg', drawing)

    if __name__ == '__main__':
        main()
`
