### ISSUE TITLE
the error in   ./make.sh

### ISSUE THREAD

**Issue by ladybirdhui** [zisianw/FaceBoxes.PyTorch#18]
Traceback (most recent call last):
  File "build.py", line 59, in <module>
    CUDA = locate_cuda()
  File "build.py", line 45, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOM

do you know why? thanks

**Comment by ladybirdhui** [comment]
solved

**Comment by mochaojie** [comment]
How did you solve it?
