### ISSUE TITLE
rgb取值反了

### ISSUE THREAD

**Issue by luuuyi** [zisianw/FaceBoxes.PyTorch#19]
作者你好，在data_augment.py文件中，167行 `image -= mean`这里是不是不对，mean为RGB模式的均值，但是代码截至运行到该部分image的形式还是OpenCV读进来的BGR模式，这部分我想确认下你是不是写错了

**Comment by sfzhang15** [comment]
@luuuyi 
你好，虽然这里的名字是叫[rgb_means](https://github.com/zisianw/FaceBoxes.PyTorch/blob/master/train.py#L37)，但是数值的顺序是BGR

**Comment by luuuyi** [comment]
@sfzhang15 嗯嗯 感谢回复
