### ISSUE TITLE
正负样本匹配策略

### ISSUE THREAD

**Issue by luuuyi** [zisianw/FaceBoxes.PyTorch#20]
作者你好，论文里面负样本比正样本是3，但是代码里面是7，不知道你有没有比例为3的实验结果，检测精度差别大么。

**Comment by zisianw** [comment]
Hi @luuuyi, you may refer to [this post](https://github.com/sfzhang15/FaceBoxes/issues/6) in the official release. In PyTorch re-implementation we did not run an experiment with negposratio: 3
