### ISSUE TITLE
data_argument.py速度优化

### ISSUE THREAD

**Issue by wang-kangkang** [zisianw/FaceBoxes.PyTorch#21]
在data_argument.py中，将distort放在了_crop的前面，这将导致速度慢很多倍。改这个也很简单，建议抽空改一下。

**Comment by zisianw** [comment]
Hi @wang-kangkang, Thanks! changing the order indeed reduces the augmentation time. I'll update the codes along with other changes.

**Comment by zisianw** [comment]
Updated in commit [f8292fe](https://github.com/zisianw/FaceBoxes.PyTorch/commit/f8292fe3fea03f3974fdde5764574e78b05ea5e8).
