### ISSUE TITLE
给priors分配ground truth的一些疑惑

### ISSUE THREAD

**Issue by Michael3444** [zisianw/FaceBoxes.PyTorch#22]
box_utils.py脚本里的match函数在给priors分配ground truth的时候，进行了ignore hard ground truth的步骤，也就是和某个ground truth最大的iou小于0.2时， 该ground truth 会被舍弃，如果其中有被舍弃的gt，那么ground truth的index就会改变，后面再做# ensure every gt matches with its prior of max overlap的时候是不是就不对了？这部分有点不理解

**Comment by Michael3444** [comment]
虽然绝大部分都样本该步骤是多余的，我认为在得到valid_gt_idx之后，应该对truths， labels， overlaps都做一次truths[valid_gt_idx]， labels[valid_gt_idx]， overlaps[valid_gt_idx]，这样gt的index才不会混乱。

**Comment by zisianw** [comment]
Hi @Michael3444, that’s indeed something to be fixed. We will look into it and update the codes. Thanks for reporting!

**Comment by zisianw** [comment]
Fixed in commit [#d29219d](https://github.com/zisianw/FaceBoxes.PyTorch/commit/d29219dc18f21d860d70abaef27b72c5e9f0dac2).

**Comment by Michael3444** [comment]
@zisianw Thanks a lot，this repo helps me a lot  :)

**Comment by zisianw** [comment]
@Michael3444 I'm glad you find it helpful. Thanks for pointing out the errors too.
