### ISSUE TITLE
Draw Box

### ISSUE THREAD

**Issue by chungyau97** [zisianw/FaceBoxes.PyTorch#23]
How to draw box of face?

**Comment by zisianw** [comment]
Hi @chungyau97, you may refer to some tutorials online discussing object detection. I usually use cv2.rectangle for bounding box visualization

**Comment by chungyau97** [comment]
Am I doing this the correct way? Because I saw caffe method is way shorter and neat than mine 
![image](https://user-images.githubusercontent.com/33013947/54247591-81efa580-4574-11e9-9f0d-0636c616c270.png)
