### ISSUE TITLE
Speed fps in real time is very slow

### ISSUE THREAD

**Issue by damvantai** [zisianw/FaceBoxes.PyTorch#26]

**Comment by chungyau97** [comment]
I manage to get average of 10fps for 720p
I manage to get average of 18-20fps for 480p

**Comment by zisianw** [comment]
Hi, you may refer to the official faceboxes implemented in Caffe for the reported numbers in paper.

**Comment by kongshuchen** [comment]
> I manage to get average of 18-20fps for 480p

what is you GPU version?

**Comment by kongshuchen** [comment]
> Hi, you may refer to the official faceboxes implemented in Caffe for the reported numbers in paper.

Can you show me the speed on gpu with gpu version and cpu?

**Comment by xsacha** [comment]
With this model as-is for 1920x1080.
60 fps on Windows with GTX 1060.
6 fps on Windows with i7-7700HQ.
All running synchronously.

**Comment by quancq** [comment]
How can i resize test image to vga resolution to obtain fps 20 on cpu or fps 125 on gpu with mAP 95.44% on FDDB dataset follow performance in paper. 
Is `img = cv2.resize(img, (640,480), interpolation=cv2.INTER_LINEAR)` correct?

**Comment by xsacha** [comment]
@quancq yes that is correct. It has to be inter linear.

**Comment by visonpon** [comment]
it seems there is a huge inference speed between this reproduce and the official ?
according to my own test, the inference time based on this code  is 15-20fps(TITAN,linux)
@zisianw

**Comment by xsacha** [comment]
@visonpon is this in your own project or this project?

With the model as-is, I got about 320 fps on Titan V for Windows (CUDA CORES / 16 as a general rule). Inference time (latency) of 2ms on a Tesla P4 (160 fps), 5ms on an RTX 2060 (120 fps).

This is with latest pytorch nightly.

The performance is one of the reasons I picked this project after evaluating similar models.

**Comment by visonpon** [comment]
@xsacha based on this project.
when my input image's size is 960*960, it's about 0.06-0.08s per image, when i resized it to half, is about 0.04-0.05s, and this speed  not contain the time extracting the face  out according the rectangle and save it .

**Comment by xsacha** [comment]
@visonpon 
Sounds like you are using test code in this project. I get a similar time on this. You need to JIT the model to have it optimised.

1. Change the ReLU inplace=True to inplace=False
2. After loading model with grad guard on, do:
torch.jit.trace(model, torch.randn(1,3,1024,1024)).save('faceboxes.pt')
3. Now do inference with this model, i.e. model = torch.jit.load('faceboxes.pt')

Your new model should be about 3MB (excluding debug pickle on 1.2.0).

I get 0.002s for images around 1024x768 - 1920x1080 on a Tesla P4 but the latency isn't as important as the CUDA core usage.

**Comment by visonpon** [comment]
@xsacha thanks for your patient response and advice~
