### ISSUE TITLE
How to draw face box correctly on original images?

### ISSUE THREAD

**Issue by discipleofhamilton** [zisianw/FaceBoxes.PyTorch#27]
I ran test.py and output the txt file. But I wanted to see the face boxes, drawing rectangles to mark the faces on the original image. Here comes the problem. No matter in which datasets, there always draw the wrong part. and the rate is high.  By the way, I can not use numpy.ndarray(original image) instead of tensor type.

![2](https://user-images.githubusercontent.com/8478501/54408869-bc954180-471e-11e9-87fa-2d8e6639fe90.jpg)
![3](https://user-images.githubusercontent.com/8478501/54408875-c28b2280-471e-11e9-942e-d6b7e3218807.jpg)
![5](https://user-images.githubusercontent.com/8478501/54408877-cdde4e00-471e-11e9-8ca0-e972c218f8a7.jpg)

It is PASCAL dataset.

**Comment by chungyau97** [comment]
![image](https://user-images.githubusercontent.com/33013947/54417828-3557c600-473e-11e9-91ac-89afd6fe6e24.png)

**Comment by discipleofhamilton** [comment]
I have already done that.

![Faceboxes_Pytorch_draw_face_boxes_wrong](https://user-images.githubusercontent.com/8478501/54420459-01cc6a00-4745-11e9-8f33-774a4b4b1092.png)

**Comment by zisianw** [comment]
Hi @discipleofhamilton the image you posted only show one box per image, is it possible that it draws only the last box in `dets`? If yes, keep `cv2.rectangle` in the for loop as you draw boxes. You could also add something like `cv2.putText(plot_image, "%.2f" % dets[i,4], (xmin, ymin), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 255, 0), lineType=cv2.LINE_AA)` to check conf score.

**Comment by discipleofhamilton** [comment]
@zisianw ok, I will try. If it's work. I will close the issue.
Thank you a lot.
