### ISSUE TITLE
Weights for loc and clf during training

### ISSUE THREAD

**Issue by alexandrali3** [zisianw/FaceBoxes.PyTorch#29]
@zisianw Hi author! I am trying to train the model. And I have some questions about the weights for loc and clf during training.
The weights for loc is 2 and for clf is 1 in both the Caffe and Pytorch official code currently. I am wondering about the weights for loc and clf during training, do they need to be changed? In other words, is there any tricks during training when setting these two weights?
Thank you!

**Comment by zisianw** [comment]
Hi @alexandrali3, the `loc` weight in PyTorch implementation follows official Caffe version to be 2. If I remember correctly, the difference is not significant. It is also not changed throughout the training session.

**Comment by alexandrali3** [comment]
@zisianw I get it. Thank you for your useful response! :D
