### ISSUE TITLE
Image Pyramid or Anchor Boxes Pyramid? 

### ISSUE THREAD

**Issue by chungyau97** [zisianw/FaceBoxes.PyTorch#30]
Correct me if I'm wrong:
Based on the research paper of SSD: 
It's using anchor boxes pyramid to detect object with various scales.

Faceboxes:
It's only using anchor boxes pyramid to detect object with various scales without using image pyramid right?

Based on faster-rcnn they are using RPN (region proposal network) to predict region of interest.
How is faceboxes and ssd doing that to detect object? 

Are the outputs (feature map) for each inception and conv in-channel and out-channel( default anchor boxes) the loc, confidence and box dimension in faceboxes.py? 

How is the default anchor boxes is used inside the coding part (faceboxes.py)? Can't find any anchor initialization in faceboxes.py

**Comment by zisianw** [comment]
Hi @chungyau97, anchor boxes are initialized in `prior_box.py`. You could refer to the `test.py` to understand how the output from network and prior boxes are used for detection.

**Comment by chungyau97** [comment]
@zisianw 
Correct me if I'm wrong,

During the output it return location(bx, by, bw, bh)(regression), confidence/probability/score(classifier) and out[2] (Box Dimension will be use in priorbox for normalization, to correct the output of location to match original image size) Based on your expalnation. (https://github.com/zisianw/FaceBoxes.PyTorch/issues/24#issuecomment-474655832). After that, you will use non-maximum suppression method to finalize the detection.

Based on the coding you wrote, you keep getting feature map in MSCL and append it to sources at (Inception3, conv3_2 and conv4_2). Then you permute the sources into a sequence of [0, 2, 3, 1] to feed it into multibox (3 conv layer in a sequential order). After getting the result you will append it back to loc and conf. 
1. Why do we need to permute sources to [0, 2, 3, 1] ?

**Comment by zisianw** [comment]
Hi @chungyau97, `detection_dimension` is not used for normalization, they are used to dense prior boxes in corresponding feature map. permute is done such that the tensor layout is converted from NCHW to NHWC, which makes it easier to combine predictions from different layers. This implementation is similar to SSD in Caffe code. You may take a look.
