### ISSUE TITLE
about Face-box filter

### ISSUE THREAD

**Issue by foralliance** [zisianw/FaceBoxes.PyTorch#31]
@zisianw 
@sfzhang15 
HI

根据paper的描述：
`Face-box filter: We keep the overlapped part of the face box if its center is in the above processed image, then filter out these face boxes whose height or width is less than 20 pixels.`

对于**过滤height/width小于20这一步**．code中的操作是：
```
b_w_t = (boxes_t[:, 2] - boxes_t[:, 0] + 1) / w * img_dim
b_h_t = (boxes_t[:, 3] - boxes_t[:, 1] + 1) / h * img_dim
mask_b = np.minimum(b_w_t, b_h_t) > 16.0
```
此时，boxes_t的坐标还是相对于＂原始image＂的坐标，只不过排除了＂中点不在crop后的square patch的box＂．
自认为，**直接排除就行，为什么还要除以w或h，乘以img_dim呢？？**

另外，为什么不是在最后1步进行排除操作呢？即
```
boxes_t[:, :2] = np.maximum(boxes_t[:, :2], roi[:2])
boxes_t[:, :2] -= roi[:2]
boxes_t[:, 2:] = np.minimum(boxes_t[:, 2:], roi[2:])
boxes_t[:, 2:] -= roi[:2]
```
之后．此时，boxes_t的坐标是相对于＂crop后的square patch＂的坐标．**为什么不是在此时进行排除？**

**Comment by sfzhang15** [comment]
@foralliance 
1. 我们是在最终的1024x1024的图片上滤掉16以下的人脸（论文中是20以下的人脸，但是16和20差别不大），那几行命令是为了保证数据増广后，缩放到1024x1024后还有大于16的人脸，否则这张图就没有gt了，没法参与训练了。
2. 这个问题说得对，上面那几行命令应该加在crop后的代码中，因为crop之后，gt的长宽可能会变小。相关代码已修改。

**Comment by foralliance** [comment]
@sfzhang15 
谢谢！！

**Comment by hsl20130659** [comment]
你好，我最近想搞个bounding box +landmark的多任务训练，是不是不适合加crop步骤，因为landmark会根据box的坐标和高宽做变换，如果加了crop操作有可能会改变box的位置？？

还有
boxes_t[:, :2] = np.maximum(boxes_t[:, :2], roi[:2])
boxes_t[:, :2] -= roi[:2]
boxes_t[:, 2:] = np.minimum(boxes_t[:, 2:], roi[2:])
boxes_t[:, 2:] -= roi[:2]

为什么要这样处理？是取crop后的相对box坐标？但又感觉不像啊
