### ISSUE TITLE
how to import gpu_nms.pyx?

### ISSUE THREAD

**Issue by jjh930910** [zisianw/FaceBoxes.PyTorch#32]
i don't know  how to import pyx file 
error is  No module gpu_nms , cpu_nms 

C:\Users\jungho\FaceBoxes.PyTorch>python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from utils.nms_wrapper import nms
  File "C:\Users\jungho\FaceBoxes.PyTorch\utils\nms_wrapper.py", line 10, in <module>
    from cpu_nms import cpu_nms, cpu_soft_nms
ImportError: No module named 'cpu_nms'

**Comment by Smoothing97** [comment]
> i don't know how to import pyx file
> error is No module gpu_nms , cpu_nms
> 
> C:\Users\jungho\FaceBoxes.PyTorch>python test.py
> Traceback (most recent call last):
> File "test.py", line 9, in 
> from utils.nms_wrapper import nms
> File "C:\Users\jungho\FaceBoxes.PyTorch\utils\nms_wrapper.py", line 10, in 
> from cpu_nms import cpu_nms, cpu_soft_nms
> ImportError: No module named 'cpu_nms'

dalao！这个问题你解决了吗...我已经被折磨到不想用我的蹩脚英语了：（

**Comment by Qingcsai** [comment]
Could u plz tell me how did u fix it?

**Comment by 9heart1111** [comment]
> > 我不知道如何导入 pyx 文件
> > 错误是 No module gpu_nms , cpu_nms
> > C:\Users\jungho\FaceBoxes.PyTorch>python test.py 
> > Traceback（最近一次调用最后一次）：
> > 文件“test.py”，第 9 行，来自
> > utils.nms_wrapper import nms
> > 文件“C:\Users\jungho\FaceBoxes .PyTorch\utils\nms_wrapper.py”，第 10 行，来自
> > cpu_nms import cpu_nms, cpu_soft_nms 
> > ImportError：没有名为“cpu_nms”的模块
> 
> dalao！这个问题你解决了吗...我已经苦不堪言了我的蹩脚英语了：（

解决了吗？Could u plz tell me how did u fix it?
