### ISSUE TITLE
How to convert txt annotations to VOC format ?

### ISSUE THREAD

**Issue by JunMa11** [zisianw/FaceBoxes.PyTorch#34]
Thanks for the great work.
I want to train a face detector based on my local dataset.

However, my data annotation is like this: `path/image.png num_face x11 y11 x12 y12 x21 y21 x22 y22...`
```
# path/name num_face x_top left, y_top left, x_bottom right, y_bottom right...
data/image01.jpg 3 599 438 605 447 789 435 801 455 698 437 703 443 
data/image02.jpg 1 9 39 83 100 
```
Could you tell me how can I convert this annotation format to voc format?

**Comment by xsacha** [comment]
Maybe follow similar to https://github.com/zisianw/WIDER-to-VOC-annotations
