### ISSUE TITLE
尝试使用FPN将后层的特征图上采样，然后再与前面的分支进行相加，发现训练时分类损失特别小，请问这是因为什么？

### ISSUE THREAD

**Issue by dectld** [zisianw/FaceBoxes.PyTorch#36]
``Epoch:5 || epochiter: 229/403|| Totel iter 1841 || L: 1.4869 C: 0.7733||Batch time: 0.5901 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 230/403|| Totel iter 1842 || L: 1.5193 C: 0.2210||Batch time: 0.6800 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 231/403|| Totel iter 1843 || L: 1.3612 C: 0.3711||Batch time: 0.4681 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 232/403|| Totel iter 1844 || L: 1.4300 C: 0.2709||Batch time: 0.6333 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 233/403|| Totel iter 1845 || L: 1.9756 C: 0.5358||Batch time: 0.4813 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 234/403|| Totel iter 1846 || L: 1.5387 C: 1.5844||Batch time: 0.5340 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 235/403|| Totel iter 1847 || L: 1.5266 C: 0.8917||Batch time: 0.5414 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 236/403|| Totel iter 1848 || L: 1.2795 C: 0.7289||Batch time: 0.6268 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 237/403|| Totel iter 1849 || L: 1.5269 C: 0.3984||Batch time: 0.6899 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 238/403|| Totel iter 1850 || L: 1.3545 C: 0.2246||Batch time: 0.6136 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 239/403|| Totel iter 1851 || L: 1.3029 C: 0.2058||Batch time: 0.6137 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 240/403|| Totel iter 1852 || L: 1.3967 C: 0.2361||Batch time: 0.6172 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 241/403|| Totel iter 1853 || L: 1.3786 C: 1.1413||Batch time: 0.6570 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 242/403|| Totel iter 1854 || L: 1.5217 C: 0.1562||Batch time: 0.6213 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 243/403|| Totel iter 1855 || L: 1.2962 C: 0.3875||Batch time: 0.6527 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 244/403|| Totel iter 1856 || L: 1.4585 C: 0.1666||Batch time: 0.6850 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 245/403|| Totel iter 1857 || L: 1.4246 C: 0.6494||Batch time: 0.6752 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 246/403|| Totel iter 1858 || L: 1.4275 C: 0.4858||Batch time: 0.7416 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 247/403|| Totel iter 1859 || L: 1.3946 C: 0.2901||Batch time: 0.5193 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 248/403|| Totel iter 1860 || L: 1.5584 C: 0.1369||Batch time: 0.5752 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 249/403|| Totel iter 1861 || L: 1.5241 C: 0.3476||Batch time: 0.5399 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 250/403|| Totel iter 1862 || L: 1.3083 C: 0.3837||Batch time: 0.4910 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 251/403|| Totel iter 1863 || L: 1.5277 C: 0.1997||Batch time: 0.5678 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 252/403|| Totel iter 1864 || L: 1.2095 C: 0.1155||Batch time: 0.6526 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 253/403|| Totel iter 1865 || L: 1.5689 C: 0.4727||Batch time: 0.6525 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 254/403|| Totel iter 1866 || L: 1.4297 C: 0.2737||Batch time: 0.6253 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 255/403|| Totel iter 1867 || L: 1.3079 C: 0.0714||Batch time: 0.7641 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 256/403|| Totel iter 1868 || L: 1.6251 C: 0.2636||Batch time: 0.6445 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 257/403|| Totel iter 1869 || L: 1.9823 C: 0.5266||Batch time: 0.6920 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 258/403|| Totel iter 1870 || L: 1.4698 C: 0.6581||Batch time: 0.6837 sec. ||LR: 0.00100000
Epoch:5 || epochiter: 259/403|| Totel iter 1871 || L: 1.7391 C: 0.4285||Batch time: 0.7007 sec. ||LR: 0.00100000

**Comment by xsacha** [comment]
Did you also update the loss calculation to understand the FPN? Otherwise gets a bogus answer.

**Comment by dectld** [comment]
I think it is initialiaztion problem.
