### ISSUE TITLE
Evaluation on FDDB

### ISSUE THREAD

**Issue by r03922123** [zisianw/FaceBoxes.PyTorch#40]
Did you implement the elliptical regressor for transforming the predicted rectangle bounding box to eclipsed bounding box?  
Best Regards.

**Comment by xsacha** [comment]
FDDB supports rectangle bounding boxes as well.

**Comment by quancq** [comment]
can you guide me evaluate model on fddb dataset. I found [evaluation code](http://vis-www.cs.umass.edu/fddb/evaluation.tgz) (Matlab) on original website, but i dont know how to use this code. Tks @xsacha

**Comment by zhengyussss** [comment]
when i use your pre-trained model to evaluate on the FDDB dataset,i meet the error like this:
Traceback (most recent call last):
  File "test.py", line 106, in <module>
    img = cv2.resize(img, None, None, fx=resize, fy=resize, interpolation=cv2.INTER_LINEAR)
TypeError: Expected cv::UMat for argument 'src'

**Comment by xingfan-git** [comment]
@zhengyussss it seems your 'img' is None. You can test it by adding 'print(img_path)' and 'print(img_raw)' before this sentence. I guess the image path is not right. Check your floders' name first.
