### ISSUE TITLE
detection_dimension in model is redundant

### ISSUE THREAD

**Issue by xsacha** [zisianw/FaceBoxes.PyTorch#42]
The extra output, detection_dimension is redundant as it can be calculated in prior_box based on width and height already.

It also fails to trace, if you attempt to use the model through JIT as it cannot follow the logic flow.

**Comment by zisianw** [comment]
yes, they can be calculated based on the shape of input image but I find it more convenient to generate directly from the model itself without worrying about the recalculation (using kernel_size, stride, pad etc) at other parts of the code, say for example when network architecture is modified or detection is done at other layers. For deployment however, where network (or input image size) is fixed, calculating or predefining the feature map shape could be more efficient. I haven't used JIT myself, maybe register_forward_hook is another option too but I'm not sure if it is supported.

**Comment by xsacha** [comment]
In prior box you just change feature_size_map from 32,32,16,16,8,8 to width/32, height/32, width/64, height/64, width/128, height/128.

This is actually the correct feature map sizes the model employs, so it is more correct to do it this way.

Then remove detection_dimension from the model and everything continues to work.

No extra calculation required. You drop an output from the model and fix jit scripting.

**Comment by zisianw** [comment]
Doesn't width/32, height/32, width/64, height/64, width/128, height/128 work only when the input shape is 2^n and is >= 128?
For example, try input size of (128x128x3) and (127x128x3). It wouldn't work for the latter.

**Comment by xsacha** [comment]
It rounds as ceil by default. That's how python works. In C++ I use std::ceil. I use this and it works for all dimensions.
Anything under 128 will be 1 for the last feature size.

This is exactly what detection_dimension was providing.

I ran the tests and get exactly the same result.

**Comment by zisianw** [comment]
Right. I was thinking in the context of `output_h = floor(((input_h + (2 * pad) - (dilation * (kernel_size[0] - 1)) - 1)/stride) + 1)` with other parameters, but in the case for FaceBoxes, a simple ceil(width/step) would do. Thanks @xsacha! I'll update the codes.
ceil is still needed, true division is returned by default in python3 and // refers to floor division.

**Comment by xsacha** [comment]
Yes, I was using:
feature_maps = [[math.ceil(self.image_size[0] / 32), math.ceil(self.image_size[1] / 32)], [math.ceil(self.image_size[0] / 64), math.ceil(self.image_size[1] / 64)], [math.ceil(self.image_size[0] / 128), math.ceil(self.image_size[1] / 128)]]

**Comment by zisianw** [comment]
Updated in [#d065b47](https://github.com/zisianw/FaceBoxes.PyTorch/commit/d065b47b8a794e97fb0326961c0929a7ada85036) along with other clean up.
