### ISSUE TITLE
Height values are bogus

### ISSUE THREAD

**Issue by xsacha** [zisianw/FaceBoxes.PyTorch#45]
Height values returned by the model will always be wrong for testing. This is possibly due to the image aspect ratio not being 1:1.
Regardless, the width values appear to be correct and you can fix the height values by setting them equal to the width.
By removing height scores, you still get the same result in AFW and PASCAL because these tests ignore width and height (using only the centre positions). Hence, [width, height] should probably be replaced by a 'size' value, which would allow for faster training/converging.

I did a test where i changed prior_box to x,y,size and ignored the fourth value of loc returned by the model. AFW and PASCAL results are unaffected.

**Comment by zisianw** [comment]
Hi @xsacha, can you run a test on the first AFW image, `AFW/images/1004109301.jpg`? The detection result seems reasonable on my end. 
<img src="https://user-images.githubusercontent.com/20707594/57269490-3c55e180-70ba-11e9-936e-7ae2dc141d4f.jpg" width="200">
If you change width and height to a single 'size' value, doesn't it mean that you will always have square bboxes as output? In the implementation, it is intentionally written to have varying aspect ratio for output bboxes. It is also similar to the ground truth provided in WIDERFACE.

**Comment by xsacha** [comment]
Yes I will always have square boxes.
For the ground truth, I am using only the width values.

The heights seem arbitrary and do not seem to relate to anything in particular. They have the best effect of giving the wrong y locations. By only using a single size for width and height, I no longer need a y offset at all. This is true in video playback as well as for AFW and PASCAL tests.

I am training a new model with just this size and already outperforms the pretrained one here at epoch 30 with losses around 1.5-2.0.

**Comment by zisianw** [comment]
I think if you intend to have square boxes as output only then regressing 'box size' alone is doable. 
Ideally, I believe it is good to have different height and width as output to better account and have tighter match between prediction and ground truth, which itself isn't necessarily square. 
Of course, things can be done along the line of better anchor initialization or using SOTA methods such as IoUNet to have better localisation but that would be beyond the work of FaceBoxes.
Is there any example where height returned by the model are badly unreasonable compared to width value?

**Comment by xsacha** [comment]
Even in the photo you sent, while the height is more normal, it doesn't seem to capture all of the head or the chin and isn't centred on the eyes. I'm not sure what it achieves.

For me, I intend to run a localisation on it afterwards. I assume everyone else would as well as the box is fairly useless without being localised to the facial landmarks. Since I am localising anyway, the width and height isn't as important as a simple size indicator.
I found that putting the height values obtained from this model in gave worse results than setting height=width.
Since it also does not affect any of the tests, I'm not sure of the benefit.
