### ISSUE TITLE
does this project has pretrained model to finetune?

### ISSUE THREAD

**Issue by chenxu93** [zisianw/FaceBoxes.PyTorch#46]
I want to use faceboxes to fine tune my dataset, does this project has pretrained model to finetune?

**Comment by sfzhang15** [comment]
https://drive.google.com/file/d/128m1QasIwQRkrY-Eb5Epi-ShXnrZWUCQ/view

**Comment by QingL0218** [comment]
@sfzhang15 Could you give the link on BaiduYun,please? I can't open the google link.

**Comment by sfzhang15** [comment]
@QingL0218 
You can use Hoxx to download from the google link.

**Comment by QingL0218** [comment]
It works, thank you
