### ISSUE TITLE
About testing procedure

### ISSUE THREAD

**Issue by ai-niki** [zisianw/FaceBoxes.PyTorch#49]
Why do you upscale images in test.py?

```
# testing scale
    if args.dataset == "FDDB":
        resize = 3
    elif args.dataset == "PASCAL":
        resize = 2.5
    elif args.dataset == "AFW":
        resize = 1

if resize != 1:
    img = cv2.resize(img, None, None, fx=resize, fy=resize, interpolation=cv2.INTER_LINEAR)
```

It looks to me that resizing images to the training scale (1024x1024) is more logical. But the performance on benchmarks is worse (-2.3%) for some reason.

**Comment by xsacha** [comment]
See: https://github.com/zisianw/FaceBoxes.PyTorch/pull/37

You can use 1024 too, it makes no difference but improves performance compared to test.py.

The size you want depends on the minimum face size you want to detect
