### ISSUE TITLE
Evaluate on WiderFace val

### ISSUE THREAD

**Issue by xiaozhuka** [zisianw/FaceBoxes.PyTorch#50]
Seems not good

Easy   Val AP: 0.8404888178724867
Medium Val AP: 0.7661765951105204
Hard   Val AP: 0.3942927175197917

**Comment by wangerwei01** [comment]
Could you share your evaluation code if you use python code? The matlab code is so inconvenient. Thank you very much.@xiaozhuka

**Comment by zisianw** [comment]
FaceBoxes is indeed not a good option for use cases like WiderFace dataset with many small faces.

**Comment by xsacha** [comment]
@xiaozhuka scale the images much larger and you will pick up the small faces better
Will make it very slow though because that's not the intention of faceboxes. Pretty sure faces < 16 pixels are excluded from training too.
