### ISSUE TITLE
模型测试

### ISSUE THREAD

**Issue by hsl20130659** [zisianw/FaceBoxes.PyTorch#53]
你好，为什么你的模型需要对原图放大三倍后做测试检测率才会高一点？这样对1080p来说确实是一个挑战，请问有什么好的改进建议吗？

**Comment by zisianw** [comment]
Hi @hsl20130659, depending on your use cases, FaceBoxes may or may not be good enough. Enlarging the image would scale up the size of small faces thus improving the performance if your image contains many small faces. You could also modify the network and explore improvement along the line of utilising detection layers at early blocks (stride 8,16 for example) such as those commonly seen in SOTA face detection model.
