### ISSUE TITLE
data_augment.py _crop , return ?

### ISSUE THREAD

**Issue by foocker** [zisianw/FaceBoxes.PyTorch#60]
is not a bug in the loop?

**Comment by zisianw** [comment]
Hi @foocker, thanks for your interest. Can you elaborate more, which line are you referring to?

**Comment by foocker** [comment]
> 
> 
> Hi @foocker, thanks for your interest. Can you elaborate more, which line are you referring to?

[https://github.com/zisianw/FaceBoxes.PyTorch/blob/master/data/data_augment.py]
function _crop the last two line, 62 and 63. the last return seems redundance.

**Comment by foocker** [comment]
By the way, why don't you add AlignModule to this model? lately, i've been adding the five point module to FaceBoxes, but i'm not sure it is good or not...

**Comment by foocker** [comment]
> 
> 
> Hi @foocker, thanks for your interest. Can you elaborate more, which line are you referring to?

soory, it's my wrong! but some place i can't understand yet...
such line 48: boxes_t[:, 2:] -= roi[:2]  , why -=

in addition, when the data is AFLW, in one image, just have one person mostly, this _crop function  
will be  work in high efficiency?

**Comment by zisianw** [comment]
> soory, it's my wrong! but some place i can't understand yet...
> such line 48: boxes_t[:, 2:] -= roi[:2] , why -=

No worries. After getting the coordinates of the training patch, the coordinates of the face boxes need to be updated too, and this is done via the line you mentioned.

> in addition, when the data is AFLW, in one image, just have one person mostly, this _crop function
> will be work in high efficiency?

_crop crops a patch from the original image, check and filter for valid face boxes and return the results. You can try isolating the function itself and check the results for a better understanding of its effect and see if it's suitable for your use case.

**Comment by foocker** [comment]
> > soory, it's my wrong! but some place i can't understand yet...
> > such line 48: boxes_t[:, 2:] -= roi[:2] , why -=
> 
> No worries. After getting the coordinates of the training patch, the coordinates of the face boxes need to be updated too, and this is done via the line you mentioned.
> 
> > in addition, when the data is AFLW, in one image, just have one person mostly, this _crop function
> > will be work in high efficiency?
> 
> _crop crops a patch from the original image, check and filter for valid face boxes and return the results. You can try isolating the function itself and check the results for a better understanding of its effect and see if it's suitable for your use case.

thank u for your replay, i will do some more experiments.
