### ISSUE TITLE
GPU version

### ISSUE THREAD

**Issue by xingfan-git** [zisianw/FaceBoxes.PyTorch#62]
Hi, does someone know where is "cpu_nms.py" and "gpu_nms.py" ? There will be import error as I import nms_wrapper, so that I can only test cpu version right now.
Could the author or someone help me out please?

**Comment by zisianw** [comment]
The files are located [here](https://github.com/zisianw/FaceBoxes.PyTorch/tree/master/utils/nms). Did you compile the nms beforehand by doing `bash make.sh`?
Could you also check if this method helps? https://github.com/zisianw/FaceBoxes.PyTorch/issues/28#issuecomment-518920921

**Comment by xingfan-git** [comment]
@xingfan-git Sorry for late replying. I'll try it today, thx!
