### ISSUE TITLE
Conf view in model does not allow batching

### ISSUE THREAD

**Issue by xsacha** [zisianw/FaceBoxes.PyTorch#63]
https://github.com/zisianw/FaceBoxes.PyTorch/blob/55b9d62cc6ec558b43e177eea1681a72ae43d05b/models/faceboxes.py#L144

I think this line should view with batch size the same as the training line.

**Comment by zisianw** [comment]
Hmm doesn't batching complicates things since images are not necessarily of the same dimension during testing, which will require more modification on `test.py` and may not be useful on common benchmark dataset? Training is fine though since they're all 1024x1024

**Comment by xsacha** [comment]
Well I only batch images when I can (eg. same resolution).
I do this on video and videos are often the same resolutions (720p, 1080p 4k) so it batches quite well.
If I'm doing 10x 1080p videos at the same time (which faceboxes allows) on my laptop, I see massive improvements when using batching. CUDA utilisation is only 50%.

Of course for your testing there may be little benefit if they are all different sizes, but it is good to have the option there.

**Comment by zisianw** [comment]
Hmm right, I'll update the model file and leave it with batching option in this case.
