### ISSUE TITLE
Questions for "boxes"

### ISSUE THREAD

**Issue by wbensvage** [zisianw/FaceBoxes.PyTorch#64]
Thank you for answering.

I was reading the code and felt curious about these lines shown below in _data_augmentation.py_
```python
height, width, _ = image_t.shape
image_t = _resize_subtract_mean(image_t, self.img_dim, self.rgb_means)
boxes_t[:, 0::2] /= width
boxes_t[:, 1::2] /= height
```
Why you resize the image to 1024x1024 but normalize your bbox coordinates by using old width & height?

Thank you!

**Comment by zisianw** [comment]
Hi, bboxes' coordinates were based on cropped patch, so to normalize them to [0,1], you need to normalize according to this scale too.
