### ISSUE TITLE
make.sh doesn't work without CUDA

### ISSUE THREAD

**Issue by mark-selyaeff** [zisianw/FaceBoxes.PyTorch#67]
I want to evaluate the model using CPU according to instructions in the README file. To do that, I first need to compile NMS module. But make.sh yields the following error:

```
$ ./make.sh
Traceback (most recent call last):
  File "build.py", line 59, in <module>
    CUDA = locate_cuda()
  File "build.py", line 45, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
```

It seems that executing make.sh without CUDA being installed is impossible.

How can I overcome this problem?

**Comment by zisianw** [comment]
Hi @mark-selyaeff 
Could you try this https://github.com/zisianw/FaceBoxes.PyTorch/issues/4#issuecomment-459592536
