### ISSUE TITLE
Remove .c and .cpp files generated by Cython during building process

### ISSUE THREAD

**Issue by raikel** [zisianw/FaceBoxes.PyTorch#68]
Files cpu_nms.c and gpu_nms.cpp are generated by Cython during building process, so they may be removed from the source code. If you try to run make.sh in a system with a python version different than that used to generate these files, they may cause trouble if not deleted before run make.sh. This is due [bugs](https://github.com/cython/cython/issues/1955) in previos versions of Cython related to Python 3.7 compatibility.

**Comment by zisianw** [comment]
Hi @raikel thanks, updated! :smile:
