### ISSUE TITLE
FDDB test result

### ISSUE THREAD

**Issue by foralliance** [zisianw/FaceBoxes.PyTorch#7]
@zisianw 
@sfzhang15 
HI

配置：pytorch0.4 + python2
因为你提提供的代码是基于python3的，所以在相应位置函数加入from __future__ import division

利用提供的训练好的检测模型，基于测试代码，得到了2845幅图片的检测结果
然后送入官方提供的检测器．
**标签文件**利用的是S3FD中提供的[FDDB_annotation_ellipseList_new.txt](https://github.com/sfzhang15/SFD/blob/master/FDDB_annotation_ellipseList_new.txt)
**结果形式**是rectangle，并没有转ellipse
**检测结果**已发至2位的邮箱

最终结果在False Positives=1000时，对于DiscROC，AP只有93.9915

**Comment by sfzhang15** [comment]
@foralliance 
DiscROC在False Positives=1000时是95.4361
[testContROC.txt](https://github.com/zisianw/FaceBoxes.PyTorch/files/2770265/testContROC.txt)
[testDiscROC.txt](https://github.com/zisianw/FaceBoxes.PyTorch/files/2770266/testDiscROC.txt)

**Comment by sfzhang15** [comment]
@foralliance 
标签文件请使用官方提供的

**Comment by foralliance** [comment]
@sfzhang15 
换了官方的标签文件后，结果一致．
谢谢！！

**Comment by foralliance** [comment]
@sfzhang15 
@zisianw 

基于**官方提供的标签文件**，利用[S3FD](https://github.com/sfzhang15/SFD)中提供的＂bounding box转换工具＂**fddb_from_rectangle_to_ellipse**，将此时的检测结果转为＂ellipses形式＂后，结果只有0.955521．跟paper中的0.960还是有差异．

是不是因为对于**fddb_from_rectangle_to_ellipse中的Fit.mat文件中的提供的5个值（meanX，meanY，stdX，stdY，w）**，需要根据不同的检测结果来设置．所以此时直接利用S3FD的是不对的．

**Comment by sfzhang15** [comment]
@foralliance 
rectangle_to_ellipse对离散结果没什么影响，最多能提升0.1。论文里的96.0是用了多尺度尝试，单尺度最好应该是95.5左右，跟你的差不多。目前我们自己改进了之后，速度不变的前提下，单尺度能达到96.0+了。

**Comment by foralliance** [comment]
@sfzhang15 
谢谢！
关于改进，不知道是否方便分享一些经验！！麻烦了！！

**Comment by sfzhang15** [comment]
@foralliance 
相关改进还在投稿中，等出结果了会公布。
