### ISSUE TITLE
这份代码里面好像没有计算mAP

### ISSUE THREAD

**Issue by songyuc** [zisianw/FaceBoxes.PyTorch#70]
老师，您好，我看了一下这份代码，好像没有计算mAP对模型进行评估，

**Comment by zisianw** [comment]
Hi @songyuc, the AP is evaluated using this [tool](https://bitbucket.org/marcopede/face-eval/src/default/), you need to download from his site

**Comment by songyuc** [comment]
Thanks for your response. I will see it in that site.
