### ISSUE TITLE
eval_tool doesn't work very well

### ISSUE THREAD

**Issue by sunnyswag** [zisianw/FaceBoxes.PyTorch#8]
Are there any other eval_tools? 
the eval_tool you recommend don't work very well,and the version is too old.
thanks!

**Comment by sfzhang15** [comment]
@sunnyswag 
How the recommend eval_tool does not work very well?

**Comment by sunnyswag** [comment]
@sfzhang15 
1.The version is too old(2014)，I must change some code to make them work.
2.There are no tutorial of how to use it in google,although I can use it by reading the readme.
BTW,can you provide some guidance of how to train the custom data or some links to this ?
thank you !

**Comment by sfzhang15** [comment]
@sunnyswag 
Sorry, the eval_tool is not our work. You can refer to ‘Face Detection without Bells and Whistles’.
