### ISSUE TITLE
Plot AP Error on FDDB_det.txt

### ISSUE THREAD

**Issue by colorjam** [zisianw/FaceBoxes.PyTorch#85]
Hi, thank you for your interesting work.
I use `python plot_AP_fddb.py ../eval/FDDB_det.txt` to evaluate the result on the FDDB dataset.
The results are generated by `python test.py --dataset FDDB`.
However, I got the following error:
```
    ......
    Line #21998 (got 5 columns instead of 1)
```
It seems `FDDB_det.txt` needs to be transformed into some other format?

**Comment by fancyshun** [comment]
do you solve this problem? I get the same problem
