### ISSUE TITLE
_resize_subtract_mean() don't adjust the values of landmarks?

### ISSUE THREAD

**Issue by Tallisgo** [zisianw/FaceBoxes.PyTorch#86]
_resize_subtract_mean() in data_augment.py resize img to 640*640 but do not adjust the landmarks?  whether  the landmarks need to change? If not ,I hope you can tell me the reason. I will be appreciate it very much.

**Comment by Tallisgo** [comment]
@zisianw

**Comment by zisianw** [comment]
Hi @programm-liang, sorry for the late reply. The coordinates are transformed into a normalized form i.e. [0,1]. Hence they are not affected by image resize since they stay the same in terms of normalized form.
